// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "app/db/models"

type (
	RiverJobState = models.RiverJobState
)

func allRiverJobState() []RiverJobState {
	return models.AllRiverJobState()
}
